basePath: /test_task/api
definitions:
  models.User:
    properties:
      age:
        type: integer
      name:
        type: string
      occupation:
        type: string
      salary:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: Swagger API for Golang Project Blueprint.
  title: Blueprint Swagger API
  version: "1.0"
paths:
  /test_task/api/user:
    post:
      consumes:
      - application/json
      description: Add user in data base
      operationId: add-user
      parameters:
      - description: user info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - text/plain
      responses:
        "202":
          description: Accepted
          schema:
            type: integer
        "500":
          description: write data in db error
          schema:
            type: string
      summary: Add user
      tags:
      - users
  /test_task/api/user/{id}:
    get:
      consumes:
      - application/json
      description: Get user from db
      operationId: get-user
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "404":
          description: user not found
          schema:
            type: string
        "500":
          description: Error encoding to json
          schema:
            type: string
      summary: Get user
      tags:
      - users
  /test_task/api/users:
    get:
      consumes:
      - application/json
      description: Get all user from db
      operationId: all-users
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "204":
          description: no users in db
          schema:
            type: string
        "500":
          description: Error encoding to json
          schema:
            type: string
      summary: Get all user
      tags:
      - users
swagger: "2.0"
